module.exports = {
    GENERATE_VIDEO_THUMBNAIL_QUEUE: 'GENERATE_VIDEO_THUMBNAIL_QUEUE',

    TRANSCRIBE_VIDEO_QUEUE: 'TRANSCRIBE_VIDEO_QUEUE',
    TRANSCRIBE_VIDEO_STARTED_QUEUE: 'TRANSCRIBE_VIDEO_STARTED_QUEUE',
    TRANSCRIBE_VIDEO_FINISHED_QUEUE: 'TRANSCRIBE_VIDEO_FINISHED_QUEUE',
    TRANSCRIBE_FINISH_QUEUE: 'TRANSCRIBE_FINISH_QUEUE',
    TRANSCRIBE_VIDEO_FAILED_QUEUE: 'TRANSCRIBE_VIDEO_FAILED_QUEUE',
    TRANSCRIBE_SUBVIDEOS_QUEUE: 'TRANSCRIBE_SUBVIDEOS_QUEUE',
    
    CONVERT_VIDEO_TO_ARTICLE_QUEUE: 'CONVERT_VIDEO_TO_ARTICLE_QUEUE',
    CONVERT_VIDEO_TO_ARTICLE_FINISH_QUEUE: 'CONVERT_VIDEO_TO_ARTICLE_FINISH_QUEUE',

    TRANSLATE_ARTICLE_TEXT_QUEUE: 'TRANSLATE_ARTICLE_TEXT_QUEUE',
    TRANSLATE_ARTICLE_TEXT_FINISH_QUEUE: 'TRANSLATE_ARTICLE_TEXT_FINISH_QUEUE',

    PROCESS_RECORDED_AUDIO_QUEUE: `PROCESS_RECORDED_AUDIO_QUEUE`,
    PROCESS_RECORDED_AUDIO_FINISHED_QUEUE: `PROCESS_RECORDED_AUDIO_FINISHED_QUEUE`,

    EXPORT_ARTICLE_TRANSLATION: `EXPORT_ARTICLE_TRANSLATION`,
    EXPORT_ARTICLE_TRANSLATION_FINISH: `EXPORT_ARTICLE_TRANSLATION_FINISH`,

    ARCHIVE_ARTICLE_TRANSLATION_AUDIOS: `ARCHIVE_ARTICLE_TRANSLATION_AUDIOS`,
    ARCHIVE_ARTICLE_TRANSLATION_AUDIOS_FINISH: `ARCHIVE_ARTICLE_TRANSLATION_AUDIOS_FINISH`,

    BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE: `BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE`,
    BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_FINISH: `BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_FINISH`,

    GENERATE_ARTICLE_TRANSLATION_VIDEO_SUBTITLE: `GENERATE_ARTICLE_TRANSLATION_VIDEO_SUBTITLE`,
    GENERATE_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_FINISH: `GENERATE_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_FINISH`,

    VIDEO_PROOFREADING_READY: 'VIDEO_PROOFREADING_READY',

    EXTRACT_VIDEO_BACKGROUND_MUSIC_QUEUE: 'EXTRACT_VIDEO_BACKGROUND_MUSIC_QUEUE',
    EXTRACT_VIDEO_BACKGROUND_MUSIC_FINISH_QUEUE: 'EXTRACT_VIDEO_BACKGROUND_MUSIC_FINISH_QUEUE',

    UPDATE_ARTICLE_VIDEO_SPEED: 'UPDATE_ARTICLE_VIDEO_SPEED',
    UPDATE_ARTICLE_VIDEO_SPEED_FINISH: 'UPDATE_ARTICLE_VIDEO_SPEED_FINISH',

    PROCESS_NOISECANCELLATIONVIDEO_AUDIO_QUEUE: `PROCESS_NOISECANCELLATIONVIDEO_AUDIO_QUEUE`,
    PROCESS_NOISECANCELLATIONVIDEO_AUDIO_FINISHED_QUEUE: `PROCESS_NOISECANCELLATIONVIDEO_AUDIO_FINISHED_QUEUE`,
    
    BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_AND_SIGNLANGUAGE: `BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_AND_SIGNLANGUAGE`,
    BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_AND_SIGNLANGUAGE_FINISH: `BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_AND_SIGNLANGUAGE_FINISH`,

    WHATSAPP_NOTIFY_USER_VIDEO_PROOFREADING_READY: 'WHATSAPP_NOTIFY_USER_VIDEO_PROOFREADING_READY',
}